### ISSUE TITLE
Support generating only project packages

### ISSUE THREAD

**Issue by nc6** [typeable/stackage2nix#24]
Have a flag to generate only project packages, not those from stackage.

**Comment by 4e6** [comment]
In #63 I implemented generation of a nix function `stack-yaml-packages.nix` that filters project packages from the Stackage. 

You can get only project packages by applying generated `stackagePackages` set to it:

```
let
  # generated packages
  stackagePackages  = import ./. {};
in import ./stack-yaml-packages.nix stackagePackages;
```
