### ISSUE TITLE
Make --lts-haskell flag optional

### ISSUE THREAD

**Issue by 4e6** [typeable/stackage2nix#3]
Stack environment should have some kind of lts-haskell repository available. Find a way to reuse it and make flag `--lts-haskell` optional

**Comment by Fuuzetsu** [comment]
It is unlikely most users have lts-haskell or all-cabal-hashes lying around. Even a simple flag to automatically clone and use these these would be a massive improvement. GitHub offers a tarball for every commit and branch so this should be easily doable even without messing around with git.

**Comment by 4e6** [comment]
From `lts-haskell` we need only a yaml file with Stackage config. The simplest thing would be to download single file directly from Github by direct link https://raw.githubusercontent.com/fpco/lts-haskell/master/lts-9.0.yaml
For `all-cabal-hashes` it is more complicated, we need a repo with full history. The reason is that a single version of the Haskell package may have several revisions, see [mtl](https://hackage.haskell.org/package/mtl-2.2.1/revisions/) for example. Stackage LTS config has SHA1 hash of the exact revision of the package Cabal file. When we fetch package from cabal database we try following:
- get the object (Cabal file) from all-cabal-hashes repo by SHA1 hash
- fallback to name/version path (that way we obtain the latest revision)
- fallback to system Cabal database (one in ~/.cabal directory)

Since we already got our hands dirty with git, I was planning to maintain some `--workdir` directory with these two repositories and clone/fetch them automatically during the run.
