### ISSUE TITLE
Support nightly Stackage

### ISSUE THREAD

**Issue by 4e6** [typeable/stackage2nix#37]
Should be able to generate nightly Stackage

Repo: https://github.com/fpco/stackage-nightly

**Comment by Fuuzetsu** [comment]
I'm interested. Would it not be the case of just pointing --lts-haskell to the nightly repo and things should Just Work™?

**Comment by Fuuzetsu** [comment]
Indeed I just tried this with `nightly-2017-10-11`: checked out the above repository and pointed `--lts-haskell` to it and it seems perfectly happy.

I guess part of this ticket should be about the nix wrapper also getting nightly repository but there should be no new backend code needed at least.

**Comment by 4e6** [comment]
> checked out the above repository and pointed --lts-haskell to it and it seems perfectly happy.

Yes, this approach works, that's the reason I set aside this issue so far. 

I don't have a clear idea on how to do this properly. I'm not a fan of having an extra flag for `stackage-nightly` directory. The easiest way I can think of would be to dump `stackage-nightly` and `lts-haskell` configs into a single directory and point nix-wrapper to it.

**Comment by 4e6** [comment]
Addressed in #39
